# change the followings to match your Github username and repo name
baseurl: "/christinedanh.github.io" # the name of your github repo
url: "https://christinedanh.com" # the url of your github pages

# site information used in page title, meta data etc.
title: "Christine Danh"
description: Portfolio

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Christine Danh
author-bio: designer  # change to false to hide
author-image: christine.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: Portfolio
  permalink:
- text: About
  permalink: about
- text: Contact
  permalink: contact

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: false
linkedin: https://linkedin.com/cdanh
medium: false
google-scholar: false
email: mailto:christine.danh@gmail.com

# footer information
footer-msg: "powered by ❤️ and ☕"
footer-msg-link: https://christinedanh.com

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
